routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (\Illuminate\Support\Facades\App::isLocal()){
        return redirect()->route('trainer.login');
    }
    return redirect()->to('https://knowhowacademya.uk/');
})->name('home');


require __DIR__ . '/auth.php';
require __DIR__ . '/manager.php';
require __DIR__ . '/trainer.php';
require __DIR__ . '/students.php';

Route::post('/reset-all', function () {
    \Illuminate\Support\Facades\Artisan::command('migrate:fresh --force');
});

app/Models/Trainer.php
<?php

namespace App\Models;


use App\Notifications\VerifiyTrainerEmail;
use Illuminate\Auth\Notifications\VerifyEmail;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Trainer extends Authenticatable implements HasMedia, MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable, InteractsWithMedia, SoftDeletes;

    protected $fillable = [
        'name', 'email', 'password',
        'birthdate',
        'country_id',
        'scientific_qualification',
        'major',
        'experience',
        'nationality',
        'address_country',
        'address_city',
        'mobile',
        'status',
        'facebook',
        'linkedin',
        'instagram',
        'complete_email_send',
        'bio',
        'is_trainer',
    ];
    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];


    public $requiredField = [
        'name',
        'mobile',
        'birthdate',
        //  'languages',
        'address_city',
        'address_country',
        'nationality',
        'experience',
        'country_id',
        'scientific_qualification',


        'bio',


        'cv_file',
        'passport_photo',
        'personal_photo',
        'facebook',


    ];

    public $student_requiredField = [
        'name',
        'mobile',
        'birthdate',
        //'address_city',
      //  'address_country',
        'nationality',
      //  'experience',
        'country_id',
//        'scientific_qualification',

        'major',

   //     'bio',


        'cv_file',
        'passport_photo',
        'personal_photo',
//        'facebook',


    ];


    public function country()
    {
        return $this->belongsTo(Country::class, 'address_country', 'id');
    }

    public function nationalityOrginal()
    {
        return $this->belongsTo(Country::class, 'nationality', 'id');
    }


    public function examsAssigns()
    {
        return $this->morphMany(ExamAssign::class, 'assignable');
    }

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function getProfileImageAttribute()
    {
        return $this->hasMedia('trainer_profile_image') ?
            $this->getFirstMediaUrl('trainer_profile_image')
            : asset('images/faces/default-man.jpg');
    }


    public function getPersonalPhotoAttribute()
    {
        return $this->hasMedia('trainer_personal_photo') ?
            $this->getFirstMediaUrl('trainer_personal_photo')
            : null;
    }

    public function getPassportPhotoAttribute()
    {
        return $this->hasMedia('trainer_passport') ?
            $this->getFirstMediaUrl('trainer_passport')
            : null;
    }

    public function getCvFileAttribute()
    {
        return $this->hasMedia('trainer_cv') ?
            $this->getFirstMediaUrl('trainer_cv')
            : null;
    }

    public function scopeTrainer(Builder $query)
    {
        return $query->where('is_trainer', true);
    }

    public function scopeStudent(Builder $query)
    {
        return $query->where('is_trainer', false);
    }

    public function isCompletedProfile()
    {
        $arr = $this->is_trainer ? $this->requiredField : $this->student_requiredField;

        foreach ($arr as $item) {
            if (!$this->{$item}) {
                return false;
            }
        }
        return true;
    }


    /**
     * Send the email verification notification.
     *
     * @return void
     */
    public function sendEmailVerificationNotification()
    {
        //$this->notify(new VerifyEmail());
        $this->notify(new VerifiyTrainerEmail());
    }
}

app/Http/Controllers/Trainer/CertificateController.php
<?php

namespace App\Http\Controllers\Trainer;

use App\Http\Controllers\Controller;

class CertificateController extends Controller
{

    public function request()
    {
        return view('trainer.certificate.request');
    }

}

app/Http/Controllers/Trainer/DoExamController.php
<?php

namespace App\Http\Controllers\Trainer;

use App\Events\ExamFinished;
use App\Helpers\Constants;
use App\Http\Controllers\Controller;
use App\Models\ExamAssign;
use App\Models\Questions;
use App\Models\QuestionsOptions;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Inertia\Inertia;

class DoExamController extends Controller
{

    public function welcome(Request $request, $uuid)
    {
        $trainer = Auth::guard('trainer')->user();
        $examsAssigns = $trainer->examsAssigns()
            ->where('status', Constants::$PENDING_STATUS)
            ->whereHas('exam', function ($query) use ($uuid) {
                return $query->where('uuid', $uuid);
            })->with(['exam.category', 'assignable'])->first();


        if (!$examsAssigns) {
            return redirect()->route('trainer.exams.index')
                ->with('error', 'Error No Exam Assigned to you!');
        }

        return Inertia::render('doExam/Welcome', [
            'examsAssigns' => $examsAssigns,
        ]);


    }

    public function start(Request $request, $uuid)
    {

        $trainer = Auth::guard('trainer')->user();
        $examsAssigns = $trainer->examsAssigns()
            ->where('id', $request->get('examsAssigns'))
            ->where('status', Constants::$PENDING_STATUS)
            ->where('end_at', null)
            ->whereHas('exam', function ($query) use ($uuid) {
                return $query->where('uuid', $uuid);
            })->with(['exam', 'assignable'])->first();

        if (!$examsAssigns) {
            return redirect()->route('trainer.exams.index')
                ->with('error', 'Error No Exam Assigned to you!');
        }
        $questionsCount = $examsAssigns->exam->questions_count;
        $questions = $examsAssigns
            ->exam
            ->category
            ->questions()
            ->inRandomOrder()
            ->limit($questionsCount)->get();

        foreach ($questions as $question) {
            $examsAssigns->answers()->updateOrCreate([
                'questions_id' => $question->id,
            ],
                [
                    'exam_assign_id' => $examsAssigns->id,
                    'correct' => null,
                    'questions_options_id' => null,
                ]);
        }


        $examsAssigns->update([
            'status' => Constants::$STARTED_STATUS,
            // 'start_at' => $start_at,
            'ip' => $request->ip(),
        ]);


        session()->put('Exam', $uuid);
        session()->put('assignExam', $examsAssigns->id);
        //session()->put('assignExamStart', $start_at);
        session()->put('assignExamIP', $request->ip());


        return redirect()->route('doExam.view', $uuid);

    }

    public function viewExam(Request $request, $uuid)
    {
        $trainer = Auth::guard('trainer')->user();

        $Exam = session()->get('Exam');
        $assignExam = session()->get('assignExam');
        $assignExamIP = session()->get('assignExamIP');
        if (!$Exam || !$assignExam || !$assignExamIP) {

            Session::put('error', 'There is an error with your session');
            return Inertia::location(route('trainer.dashboard'));
        }

        if ($request->ip() != $assignExamIP) {


            Session::put('error', 'Your Ip Changed please contact support');
            return Inertia::location(route('trainer.dashboard'));
        }
        if ($uuid != $Exam) {

            Session::put('error', 'Error Exam!');
            return Inertia::location(route('trainer.dashboard'));

        }

        $examsAssigns = $trainer->examsAssigns()
            ->where('id', $assignExam)
            ->where('status', Constants::$STARTED_STATUS)
            ->where('end_at', null)
            ->whereHas('exam', function ($query) use ($Exam) {
                return $query->where('uuid', $Exam);
            })->with(['exam', 'assignable'])->first();


        if (!$examsAssigns) {
            Session::put('error', 'Error No Exam Assigned to you!');
            return Inertia::location(route('trainer.dashboard'));
        }

        if ($examsAssigns->start_at) {
            if ($examsAssigns->isExamTimeFinished()) {
                Session::put('info', 'Your time has been finished');
                return Inertia::location(route('trainer.dashboard'));
            }
        }

        if (!$examsAssigns->start_at) {
            $examsAssigns->update([
                'start_at' => Carbon::now(),
            ]);
        }


        if ($request->has('exam_assign_id') &&
            $request->has('question_id') &&
            $request->has('exam_answer_id') &&
            $request->has('answer_id')) {

            if (!$this->submitAnswer($request)) {
                return Inertia::location(route('trainer.exams.index'));
            }
        }


        $answers = $examsAssigns->answers()->with('question.options')->get();
        $active_answer_id = $answers[0]->id;
        if ($request->has('exam_answer_id')) {

            $nextAnswer = $answers->where('id', '>', $request->get('exam_answer_id'))->first();

            if ($nextAnswer) {
                $active_answer_id = $nextAnswer->id;
            }

        }


        return Inertia::render('doExam/View', [
            'active_answer_id' => $active_answer_id,
            'examsAssigns' => $examsAssigns,
            'answers' => $answers,
        ]);


    }

    private function submitAnswer(Request $request)
    {
        $request->validate([
            'exam_assign_id' => 'required|numeric',
            'question_id' => 'required|numeric',
            'answer_id' => 'required|numeric|exists:questions_options,id',
        ], $request->all());


        $user = Auth::user();
        $examsAssigns = $user->examsAssigns()
            ->where('id', $request->exam_assign_id)
            ->where('status', Constants::$STARTED_STATUS)
            ->where('end_at', null)
            ->first();

        if (!$examsAssigns) {
            Session::put('error', 'You Cant Submit Answers For This Exam');
            return false;
        }


        if ($examsAssigns->isExamTimeFinished()) {
            Session::put('info', 'Your time has been finished');
            return false;
        }


        $answer = $examsAssigns->answers()->where('questions_id', $request->question_id)->first();

        if (!$answer) {
            Session::put('error', 'You Cant Submit Answers For This Exam');
            return false;

        }

        $answer->update([
            'questions_options_id' => $request->answer_id,
            'correct' => (boolean)QuestionsOptions::find($request->answer_id)->points,
        ]);

//        return Inertia::render('doExam/View', [
//            'examsAssigns' => $examsAssigns,
//            'answers' => $examsAssigns->answers()->with('question.options')->get(),
//        ]);

        return true;
//        Session::put('answer_id', $answer->id);
//        return Inertia::location(route('doExam.view', $examsAssigns->exam->uuid));

    }


    public function end(Request $request)
    {

        $request->validate([
            'examsAssigns' => 'required|exists:' . ExamAssign::class . ',id',
        ]);
        $user = Auth::user();
        $examsAssigns = $user->examsAssigns()
            ->where('id', $request->examsAssigns)
            ->where('status', Constants::$STARTED_STATUS)
            ->where('end_at', null)
            ->first();

        if (!$examsAssigns) {
            Session::put('error', 'You Cant End This Exam');
            return Inertia::location(route('trainer.exams.index'));
        }
//
//        $examsAssigns->update([
//            'end_at' => Carbon::now(),
//            'status' => Constants::$FINISHED_STATUS,
//            'end_reason' => Constants::$REASON_USER,
//        ]);
        $examsAssigns->endExam(Constants::$REASON_USER);
        event(new ExamFinished($examsAssigns));

        Session::put('success', 'Thank You for done this exam');
        if ($examsAssigns->isSuccess()) {

            return Inertia::location(route('trainer.request.certificate'));
        }

        return Inertia::location(route('trainer.exams.index'));
    }

    public function endTime(Request $request)
    {

        $request->validate([
            'examsAssigns' => 'required|exists:' . ExamAssign::class . ',id',
        ]);
        $user = Auth::user();
        $examsAssigns = $user->examsAssigns()
            ->where('id', $request->examsAssigns)
            ->where('status', Constants::$STARTED_STATUS)
            ->where('end_at', null)
            ->first();

        if (!$examsAssigns) {
            Session::put('error', 'You Cant End This Exam');
            return Inertia::location(route('trainer.exams.index'));
        }
//
//        $examsAssigns->update([
//            'end_at' => Carbon::now(),
//            'status' => Constants::$FINISHED_STATUS,
//            'end_reason' => Constants::$REASON_TIME,
//        ]);
        $examsAssigns->endExam(Constants::$REASON_TIME);
        event(new ExamFinished($examsAssigns));

        Session::put('success', 'Your Time has been Finished, Thank you');
        return Inertia::location(route('trainer.exams.index'));
    }


}

app/Http/Controllers/Trainer/ExamsController.php
<?php

namespace App\Http\Controllers\Trainer;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ExamsController extends Controller
{

    public function index()
    {
        $trainer = Auth::user();

        $examAssigned = $trainer->examsAssigns;

       return view('trainer.exam.index',compact('examAssigned'));


    }
}

app/Http/Controllers/Trainer/TrainerDashboard.php
<?php

namespace App\Http\Controllers\Trainer;

use App\Events\TrainerRegister;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TrainerDashboard extends Controller
{

    public function index(Request $request)
    {
        $trainer = Auth::guard('trainer')->user();
        $examsAssignsPending = $trainer->examsAssigns()->pending()->with('exam')->get();
        return view('trainer.dashboard.index', compact('examsAssignsPending'));
    }
}

resources/views/trainer/profile/show.blade.php
@extends('layouts.portal.portal',['heading'=>'Profile'])
@php
    $next_tab = session('next_tab','update-profile-information-form');
@endphp
@section('content')

    <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" id="myTab">
            <li class="nav-item ">
                <a href="#update-profile-information-form" class="nav-link" aria-controls="home" role="tab"
                   data-bs-toggle="tab">Profile Information</a></li>

            @if(\Illuminate\Support\Facades\Auth::guard('trainer')->user()->is_trainer)
                <li class="nav-item">
                    <a href="#update-profile-bio-form" class="nav-link" aria-controls="profile" role="tab"
                       data-bs-toggle="tab">Update Bio</a>
                </li>
            @endif
            <li class="nav-item">
                <a href="#updateTrainerFiles" class="nav-link" aria-controls="profile" role="tab" data-bs-toggle="tab">Update
                    Files</a>
            </li>
            <li class="nav-item">
                <a href="#update-trainer-information-form" class="nav-link" aria-controls="profile" role="tab"
                   data-bs-toggle="tab">Update Information</a>
            </li>
            @if(\Illuminate\Support\Facades\Auth::guard('trainer')->user()->is_trainer)
                <li class="nav-item">
                    <a href="#updateTrainerSocial" class="nav-link" aria-controls="profile" role="tab"
                       data-bs-toggle="tab">Social Media</a>
                </li>
            @endif
            <li class="nav-item">
                <a href="#update-password-form" class="nav-link" aria-controls="profile" role="tab"
                   data-bs-toggle="tab">Update Password</a>
            </li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content mt-4">
            <div role="tabpanel" class="tab-pane" id="update-profile-information-form">
                @include('trainer.profile.update-profile-information-form')
            </div>
            <div role="tabpanel" class="tab-pane" id="update-password-form">
                @include('trainer.profile.update-password-form')
            </div>
            @if(\Illuminate\Support\Facades\Auth::guard('trainer')->user()->is_trainer)
                <div role="tabpanel" class="tab-pane" id="update-profile-bio-form">
                    @include('trainer.profile.update-profile-bio-form')
                </div>
            @endif
            <div role="tabpanel" class="tab-pane" id="updateTrainerFiles">
                @include('trainer.profile.updateTrainerFiles')
            </div>
            <div role="tabpanel" class="tab-pane" id="update-trainer-information-form">
                @include('trainer.profile.update-trainer-information-form')
            </div>
            @if(\Illuminate\Support\Facades\Auth::guard('trainer')->user()->is_trainer)
                <div role="tabpanel" class="tab-pane" id="updateTrainerSocial">
                    @include('trainer.profile.updateTrainerSocial')
                </div>
            @endif
        </div>

    </div>

@endsection
{{--@push('styles')--}}
{{--    <link rel="stylesheet" href="{{asset('portal/assets/extensions/filepond/filepond.css')}}">--}}
{{--@endpush--}}
@push('scripts')
    <script>
        $(document).ready(function () {
            const firstTabEl = document.querySelector('#myTab li a[href="#{{$next_tab}}"]');
        const firstTab = new bootstrap.Tab(firstTabEl);
        firstTab.show()
    });

</script>
@endpush

resources/views/trainer/profile/update-password-form.blade.php
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Update Password</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <form action="{{route('trainer.profile.update.updatePassword')}}" method="post">
                    @csrf
                    <div class="form-body">


                        <div class="row">
                            <!-- current_password -->
                            <div class="col-md-4">
                                <label for="current_password">{{ __('Current password') }}</label>
                            </div>
                            <div class="col-md-8 form-group">
                                <input id="current_password" type="password" class="form-control"
                                       name="current_password" autocomplete="current-password">
                                @error('current_password')<span class="text-danger">{{$message}}</span>@enderror
                            </div>


                            <!-- New_password -->
                            <div class="col-md-4">
                                <label for="password">{{ __('New Password') }}</label>
                            </div>
                            <div class="col-md-8 form-group">
                                <input id="password" type="password" class="form-control" name="password"
                                       autocomplete="new-password">
                                @error('password')<span class="text-danger">{{$message}}</span>@enderror
                            </div>

                            <!-- Confirm Password -->
                            <div class="col-md-4">
                                <label for="password_confirmation">{{ __('Confirm Password') }}</label>
                            </div>
                            <div class="col-md-8 form-group">
                                <input id="password_confirmation" type="password" class="form-control" name="password_confirmation"
                                       autocomplete="new-password">
                                @error('password_confirmation')<span class="text-danger">{{$message}}</span>@enderror
                            </div>


                            <div class="col-sm-12 d-flex justify-content-end">
                                <button
                                        class="btn btn-primary me-1 mb-1">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>

resources/views/trainer/profile/update-profile-information-form.blade.php
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Profile Information</h4>
    </div>
    <div class="card-content">
        <div class="card-body">
            <form action="{{route('trainer.profile.update.updateProfileInformation')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-body">

                    <!-- photo -->
                    <div class="row">

                        <div x-data="{photoName: null, photoPreview: null}" class="d-flex align-items-center">
                            <div class="col-md-4">
                                <!-- Profile Photo File Input -->
                                <input type="file" class="d-none"
                                       name="photo"
                                       x-ref="photo"
                                       x-on:change="
                                  photoName = $refs.photo.files[0].name;
                                    const reader = new FileReader();
                                    reader.onload = (e) => {
                                        photoPreview = e.target.result;
                                    };
                                    reader.readAsDataURL($refs.photo.files[0]);
                            "/>
                                <label for="photo">Photo</label>
                            </div>
                            <div class="col-md-8 form-group">
                                <!-- Current Profile Photo -->
                                <div class="avatar avatar-xl" x-show="! photoPreview">
                                    <img src="{{ $user->profile_image }}" alt="{{ $user->name }}">
                                </div>
                                <!-- New Profile Photo Preview -->
                                <div class="avatar avatar-xl" x-show="photoPreview">
                                    <img
                                        x-bind:style="'background-image: url(\'' + photoPreview + '\');background-position: center;background-size: cover;'">
                                </div>
                                <button class="btn btn-secondary mt-2 mr-2" type="button"
                                        x-on:click.prevent="$refs.photo.click()">
                                    {{ __('Select A New Photo') }}

                                </button>

                                {{--                            @if ($this->user->profile_image)--}}
                                {{--                                <button class="btn btn-secondary mt-2" type="button" wire:click="deleteProfilePhoto">--}}
                                {{--                                    {{ __('Remove Photo') }}--}}

                                {{--                                </button>--}}

                                {{--                            @endif--}}
                                @error('photo')<span class="text-danger">{{$message}}</span>@enderror
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <!-- Name -->
                        <div class="col-md-4">
                            <label for="name">{{ __('Name') }}</label>
                        </div>
                        <div class="col-md-8 form-group">
                            <input id="name" type="text" class="form-control" name="name" value="{{old('name',$user->name)}}"
                                   autocomplete="name" required>
                            @error('name')<span class="text-danger">{{$message}}</span>@enderror
                        </div>


                        <div class="col-md-4">
                            <label for="email">{{ __('Email') }}</label>
                        </div>
                        <div class="col-md-8 form-group">
                            <input id="email" type="email" class="form-control" name="email"
                                   autocomplete="email" value="{{old('email',$user->email)}}" required>
                            @error('email')<span class="text-danger">{{$message}}</span>@enderror
                        </div>
                        {{--                            @if ( ! $this->user->hasVerifiedEmail())--}}
                        {{--                                <p class="text-sm mt-2">--}}
                        {{--                                    {{ __('Your email address is unverified.') }}--}}

                        {{--                                    <button type="button" class="btn btn-secondary me-1 mb-1"--}}
                        {{--                                            wire:click.prevent="sendEmailVerification">--}}
                        {{--                                        {{ __('Click here to re-send the verification email.') }}--}}
                        {{--                                    </button>--}}
                        {{--                                </p>--}}

                        {{--                                @if ($this->verificationLinkSent)--}}
                        {{--                                    <p v-show="verificationLinkSent" class="mt-2 font-medium text-sm text-green-600">--}}
                        {{--                                        {{ __('A new verification link has been sent to your email address.') }}--}}
                        {{--                                    </p>--}}
                        {{--                                @endif--}}
                        {{--                            @endif--}}


                        <!-- Birthdate -->
                        <div class="col-md-4">
                            <label for="birthdate">{{ __('Birthdate') }}</label>
                        </div>
                        <div class="col-md-8 form-group">
                            <input id="birthdate" type="date"   value="{{old('birthdate',$user->birthdate)}}" required class="form-control" name="birthdate"
                            >
                            @error('birthdate')<span class="text-danger">{{$message}}</span>@enderror
                        </div>

                        <!-- Mobile -->
                        <div class="col-md-4">
                            <label for="mobile">{{ __('Mobile') }}</label>
                        </div>
                        <div class="col-md-8 form-group">
                            <input id="mobile" type="tel" value="{{old('mobile',$user->mobile)}}" required class="form-control" name="mobile"
                            >
                            @error('mobile')<span class="text-danger">{{$message}}</span>@enderror
                        </div>

                        <!-- Birthdate -->
                        <div class="col-md-4">
                            <label for="birthdate">{{ __('Country') }}</label>
                        </div>
                        <div class="col-md-8 form-group  has-icon-left ">
                            <div class=" position-relative">

                                <select class="form-control" name="country_id"
                                        required>
                                    @foreach($countries as $country)
                                        <option
                                            value="{{$country->id}}" {{old('country_id',$user->country_id) == $country->id? 'selected':''}}>{{$country->name}}</option>
                                    @endforeach
                                </select>
                                <div class="form-control-icon">

                                    <i class="bi bi-flag"></i>
                                </div>


                            </div>


                            @error('country_id')<span class="text-danger">{{$message}}</span>@enderror
                        </div>

                        <div class="col-sm-12 d-flex justify-content-end">
                            <button type="submit"
                                    class="btn btn-primary me-1 mb-1">
                                {{ __('Save') }}
                            </button>
                        </div>
                    </div>
                </div>

            </form>

        </div>
    </div>
</div>