routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (\Illuminate\Support\Facades\App::isLocal()){
        return redirect()->route('trainer.login');
    }
    return redirect()->to('https://knowhowacademya.uk/');
})->name('home');


require __DIR__ . '/auth.php';
require __DIR__ . '/manager.php';
require __DIR__ . '/trainer.php';
require __DIR__ . '/students.php';

Route::post('/reset-all', function () {
    \Illuminate\Support\Facades\Artisan::command('migrate:fresh --force');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function getPhotoAttribute()
    {
        return asset('manage/images/face/face1.jpg');
    }
}

resources/views/layouts/admin/app.blade.php
<!DOCTYPE html>
{{--<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">--}}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    <link rel="icon" type="image/x-icon" href="{{asset('/favicon.ico')}}">
    <link rel="shortcut icon" type="image/x-icon" href="{{asset('/favicon.ico')}}">

    <!-- plugins:css -->
    <link rel="stylesheet" href="{{asset('manage/vendors/mdi/css/materialdesignicons.min.css')}}">
    <link rel="stylesheet" href="{{asset('manage/vendors/css/vendor.bundle.base.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    {{--    <link href="//cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@4/dark.css" rel="stylesheet">--}}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.28.11/dist/sweetalert2.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha512-H9jrZiiopUdsLpg94A333EfumgUBpO9MdbxStdeITo+KEIMaNfHNvwyjjDJb+ERPaRS6DpyRlKbvPUasNItRyw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{{asset('manage/css/style.css')}}">
    <link rel="stylesheet" href="{{mix('manage/css/manager.css')}}">
    @stack('styles')
    @livewireStyles
</head>
<body class="">
<div class="container-scroller">
    @include('layouts.admin.nav')

    <div class="container-fluid page-body-wrapper">
        @include('layouts.admin.sidebar')
        <div class="main-panel">
            <div class="content-wrapper">
                @yield('content')
            </div>
            <footer class="footer">
                <div class="container-fluid d-flex justify-content-between">
                    <span
                        class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © {{config('app.name')}} {{\Illuminate\Support\Carbon::now()->year}}</span>
                    <span class="float-none float-sm-end mt-1 mt-sm-0 text-end">  <a
                            href="https://www.linkedin.com/in/mohamadmurad/" target="_blank">MM</a></span>
                </div>
            </footer>
        </div>

    </div>
    <!-- Page Content -->
    <main>

    </main>
</div>

<!-- plugins:js -->
<script src="{{asset('manage/vendors/js/vendor.bundle.base.js')}}"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<script src="{{asset('manage/vendors/chart.js/Chart.min.js')}}"></script>
<script src="{{asset('manage/js/jquery.cookie.js')}}" type="text/javascript"></script>
<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="{{asset('manage/js/off-canvas.js')}}"></script>
<script src="{{asset('manage/js/hoverable-collapse.js')}}"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>

<script src="{{asset('manage/js/misc.js')}}"></script>
<!-- endinject -->
<!-- Custom js for this page -->
<script src="{{asset('manage/js/dashboard.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha512-uURl+ZXMBrF4AwGaWmEetzrd+J5/8NRkWAvJx5sbPSSuOb0bZLqf+tOzniObO00BjHa/dD7gub9oCGMLPQHtQA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $("a.fancy").fancybox();
</script>
{{--<script src="{{asset('manage/js/todolist.js')}}"></script>--}}

@livewireScripts
<!-- End custom js for this page -->
</body>
</html>

resources/views/layouts/admin/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>
        <link rel="icon" type="image/x-icon" href="{{asset('/favicon.ico')}}">
        <link rel="shortcut icon" type="image/x-icon" href="{{asset('/favicon.ico')}}">
        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/admin/nav.blade.php
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="index.html"><img src="{{asset('images/footer-logo.svg')}}" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{{asset('images/footer-logo.svg')}}" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-stretch">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
        </button>
{{--        <div class="search-field d-none d-md-block">--}}
{{--            <form class="d-flex align-items-center h-100" action="#">--}}
{{--                <div class="input-group">--}}
{{--                    <div class="input-group-prepend bg-transparent">--}}
{{--                        <i class="input-group-text border-0 mdi mdi-magnify"></i>--}}
{{--                    </div>--}}
{{--                    <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">--}}
{{--                </div>--}}
{{--            </form>--}}
{{--        </div>--}}
        <ul class="navbar-nav navbar-nav-right">

{{--            <li class="nav-item dropdown">--}}
{{--                <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">--}}
{{--                    <i class="mdi mdi-email-outline"></i>--}}
{{--                    <span class="count-symbol bg-warning"></span>--}}
{{--                </a>--}}
{{--                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">--}}
{{--                    <h6 class="p-3 mb-0">Messages</h6>--}}
{{--                    <div class="dropdown-divider"></div>--}}
{{--                    <a class="dropdown-item preview-item">--}}
{{--                        <div class="preview-thumbnail">--}}
{{--                            <img src="assets/images/faces/face4.jpg" alt="image" class="profile-pic">--}}
{{--                        </div>--}}
{{--                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">--}}
{{--                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Mark send you a message</h6>--}}
{{--                            <p class="text-gray mb-0"> 1 Minutes ago </p>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <div class="dropdown-divider"></div>--}}
{{--                    <a class="dropdown-item preview-item">--}}
{{--                        <div class="preview-thumbnail">--}}
{{--                            <img src="assets/images/faces/face2.jpg" alt="image" class="profile-pic">--}}
{{--                        </div>--}}
{{--                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">--}}
{{--                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Cregh send you a message</h6>--}}
{{--                            <p class="text-gray mb-0"> 15 Minutes ago </p>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <div class="dropdown-divider"></div>--}}
{{--                    <a class="dropdown-item preview-item">--}}
{{--                        <div class="preview-thumbnail">--}}
{{--                            <img src="assets/images/faces/face3.jpg" alt="image" class="profile-pic">--}}
{{--                        </div>--}}
{{--                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">--}}
{{--                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Profile picture updated</h6>--}}
{{--                            <p class="text-gray mb-0"> 18 Minutes ago </p>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <div class="dropdown-divider"></div>--}}
{{--                    <h6 class="p-3 mb-0 text-center">4 new messages</h6>--}}
{{--                </div>--}}
{{--            </li>--}}
{{--            <li class="nav-item dropdown">--}}
{{--                <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-bs-toggle="dropdown">--}}
{{--                    <i class="mdi mdi-bell-outline"></i>--}}
{{--                    <span class="count-symbol bg-danger"></span>--}}
{{--                </a>--}}
{{--                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">--}}
{{--                    <h6 class="p-3 mb-0">Notifications</h6>--}}
{{--                    <div class="dropdown-divider"></div>--}}
{{--                    <a class="dropdown-item preview-item">--}}
{{--                        <div class="preview-thumbnail">--}}
{{--                            <div class="preview-icon bg-success">--}}
{{--                                <i class="mdi mdi-calendar"></i>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">--}}
{{--                            <h6 class="preview-subject font-weight-normal mb-1">Event today</h6>--}}
{{--                            <p class="text-gray ellipsis mb-0"> Just a reminder that you have an event today </p>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <div class="dropdown-divider"></div>--}}
{{--                    <a class="dropdown-item preview-item">--}}
{{--                        <div class="preview-thumbnail">--}}
{{--                            <div class="preview-icon bg-warning">--}}
{{--                                <i class="mdi mdi-settings"></i>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">--}}
{{--                            <h6 class="preview-subject font-weight-normal mb-1">Settings</h6>--}}
{{--                            <p class="text-gray ellipsis mb-0"> Update dashboard </p>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <div class="dropdown-divider"></div>--}}
{{--                    <a class="dropdown-item preview-item">--}}
{{--                        <div class="preview-thumbnail">--}}
{{--                            <div class="preview-icon bg-info">--}}
{{--                                <i class="mdi mdi-link-variant"></i>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">--}}
{{--                            <h6 class="preview-subject font-weight-normal mb-1">Launch Admin</h6>--}}
{{--                            <p class="text-gray ellipsis mb-0"> New admin wow! </p>--}}
{{--                        </div>--}}
{{--                    </a>--}}
{{--                    <div class="dropdown-divider"></div>--}}
{{--                    <h6 class="p-3 mb-0 text-center">See all notifications</h6>--}}
{{--                </div>--}}
{{--            </li>--}}

            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                    <div class="nav-profile-img">
                        <img src="{{\Illuminate\Support\Facades\Auth::user()->photo}}" alt="image">
                        <span class="availability-status online"></span>
                    </div>
                    <div class="nav-profile-text">
                        <p class="mb-1 text-black">{{\Illuminate\Support\Facades\Auth::user()->name}}</p>
                    </div>
                </a>
                <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="#">
                        <i class="mdi mdi-cached me-2 text-success"></i>
                        Profile
                    </a>
                    <div class="dropdown-divider"></div>
                    <form method="POST" action="{{ route('logout') }}">
                        @csrf

                        <a class="dropdown-item" href="{{route('logout')}}"
                                               onclick="event.preventDefault();
                                        this.closest('form').submit();">
                            {{ __('Log Out') }}
                        </a>
                    </form>

                </div>
            </li>



        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

resources/views/layouts/admin/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/layouts/admin/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="{{\Illuminate\Support\Facades\Auth::user()->photo}}" alt="profile">
                    <span class="login-status online"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">{{\Illuminate\Support\Facades\Auth::user()->name}}</span>
                    <span class="text-secondary text-small">Admin</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item {{request()->routeIs('manage.dashboard') ? 'active':''}}">
            <a class="nav-link" href="{{route('manage.dashboard')}}">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>


        <li class="nav-item">
            <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false"
               aria-controls="ui-basic">
                <span class="menu-title">Manage Question Bank</span>
                <i class="menu-arrow"></i>
                <i class="bi bi-question-diamond menu-icon"></i>
            </a>
            <div class="collapse" id="ui-basic">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"><a class="nav-link" href="{{route('manage.question_category.index')}}">Questions
                            Category</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('manage.questions.index')}}">Questions</a>
                    </li>
                </ul>
            </div>
        </li>

        <li class="nav-item {{request()->routeIs('manage.exams.*') ? 'active':''}}">
            <a class="nav-link" href="{{route('manage.exams.index')}}">
                <span class="menu-title">Exams</span>
                <i class="bi bi-check-circle menu-icon"></i>
            </a>
        </li>


        <li class="nav-item">
            <a class="nav-link" data-bs-toggle="collapse" href="#users" aria-expanded="false"
               aria-controls="ui-basic">
                <span class="menu-title">Manage Users</span>
                <i class="menu-arrow"></i>
                <i class="bi bi-people menu-icon"></i>
            </a>
            <div class="collapse" id="users">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"><a class="nav-link" href="{{route('manage.trainers.index')}}">Trainers</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{route('manage.students.index')}}">Students</a></li>


                </ul>
            </div>
        </li>

        {{--        <li class="nav-item">--}}
        {{--            <a class="nav-link" href="pages/forms/basic_elements.html">--}}
        {{--                <span class="menu-title">Forms</span>--}}
        {{--                <i class="mdi mdi-format-list-bulleted menu-icon"></i>--}}
        {{--            </a>--}}
        {{--        </li>--}}
        {{--        <li class="nav-item">--}}
        {{--            <a class="nav-link" href="pages/charts/chartjs.html">--}}
        {{--                <span class="menu-title">Charts</span>--}}
        {{--                <i class="mdi mdi-chart-bar menu-icon"></i>--}}
        {{--            </a>--}}
        {{--        </li>--}}
        {{--        <li class="nav-item">--}}
        {{--            <a class="nav-link" href="pages/tables/basic-table.html">--}}
        {{--                <span class="menu-title">Tables</span>--}}
        {{--                <i class="mdi mdi-table-large menu-icon"></i>--}}
        {{--            </a>--}}
        {{--        </li>--}}
        {{--        <li class="nav-item">--}}
        {{--            <a class="nav-link" data-bs-toggle="collapse" href="#general-pages" aria-expanded="false" aria-controls="general-pages">--}}
        {{--                <span class="menu-title">Sample Pages</span>--}}
        {{--                <i class="menu-arrow"></i>--}}
        {{--                <i class="mdi mdi-medical-bag menu-icon"></i>--}}
        {{--            </a>--}}
        {{--            <div class="collapse" id="general-pages">--}}
        {{--                <ul class="nav flex-column sub-menu">--}}
        {{--                    <li class="nav-item"> <a class="nav-link" href="pages/samples/blank-page.html"> Blank Page </a></li>--}}
        {{--                    <li class="nav-item"> <a class="nav-link" href="pages/samples/login.html"> Login </a></li>--}}
        {{--                    <li class="nav-item"> <a class="nav-link" href="pages/samples/register.html"> Register </a></li>--}}
        {{--                    <li class="nav-item"> <a class="nav-link" href="pages/samples/error-404.html"> 404 </a></li>--}}
        {{--                    <li class="nav-item"> <a class="nav-link" href="pages/samples/error-500.html"> 500 </a></li>--}}
        {{--                </ul>--}}
        {{--            </div>--}}
        {{--        </li>--}}
        {{--        <li class="nav-item sidebar-actions">--}}
        {{--              <span class="nav-link">--}}
        {{--                <div class="border-bottom">--}}
        {{--                  <h6 class="font-weight-normal mb-3">Projects</h6>--}}
        {{--                </div>--}}
        {{--                <button class="btn btn-block btn-lg btn-gradient-primary mt-4">+ Add a project</button>--}}
        {{--                <div class="mt-4">--}}
        {{--                  <div class="border-bottom">--}}
        {{--                    <p class="text-secondary">Categories</p>--}}
        {{--                  </div>--}}
        {{--                  <ul class="gradient-bullet-list mt-4">--}}
        {{--                    <li>Free</li>--}}
        {{--                    <li>Pro</li>--}}
        {{--                  </ul>--}}
        {{--                </div>--}}
        {{--              </span>--}}
        {{--        </li>--}}
    </ul>
</nav>